// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUAv3S_Ur7A6o84v12QWbquU2_qS-wdYE',
    appId: '1:903482175639:web:336f915c72e63ce52c39d2',
    messagingSenderId: '903482175639',
    projectId: 'flutter-6f560',
    authDomain: 'flutter-6f560.firebaseapp.com',
    storageBucket: 'flutter-6f560.appspot.com',
    measurementId: 'G-PBG44SNGKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1HUmA2xenqK4CwkZGIn1-xASOCPC3Vw0',
    appId: '1:903482175639:android:10828a66b3bf61592c39d2',
    messagingSenderId: '903482175639',
    projectId: 'flutter-6f560',
    storageBucket: 'flutter-6f560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GLgkgzQ-c_fPM8iEF6tkCuno0QrjkMQ',
    appId: '1:903482175639:ios:6fcf22b309f799862c39d2',
    messagingSenderId: '903482175639',
    projectId: 'flutter-6f560',
    storageBucket: 'flutter-6f560.appspot.com',
    iosClientId: '903482175639-lnbpa747gc936d438u1g1ci1pq0jd1gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8GLgkgzQ-c_fPM8iEF6tkCuno0QrjkMQ',
    appId: '1:903482175639:ios:6fcf22b309f799862c39d2',
    messagingSenderId: '903482175639',
    projectId: 'flutter-6f560',
    storageBucket: 'flutter-6f560.appspot.com',
    iosClientId: '903482175639-lnbpa747gc936d438u1g1ci1pq0jd1gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );
}
